# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1di1hlItOQBx8cbBuNDf5dSJdcxjBAN5_
"""



# @title
import pandas as pd
import numpy as np

df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

renomear = {'work_year': 'Ano',
'experience_level': 'Nível de experiência',
'employment_type': 'Tipo de emprego',
'job_title': 'Cargo',
'salary': 'Salário',
'salary_currency': 'Moeda',
'salary_in_usd': 'Salário em dólares americanos',
'employee_residence': 'Residência do funcionário',
'remote_ratio': 'remoto',
'company_location': 'Localização da empresa',
'company_size': 'Tamanho'}

df.rename(columns=renomear, inplace=True)

renomear_experiencia = {'SE' : 'sênior', 'MI' : 'pleno', 'EN' : 'junior', 'EX' : 'CIO'}
df['Nível de experiência'] = df['Nível de experiência'].replace(renomear_experiencia)

renomear_tamanho = {'M' : 'médio', 'L' : 'grande', 'S' : 'pequena'}
df['Tamanho'] = df['Tamanho'].replace(renomear_tamanho)

renomear_tempo = {'FT' : 'integral', 'CT' : 'por contrato', 'PT' : 'meio periodo', 'FL' : 'freelance' }
df['Tipo de emprego'] = df['Tipo de emprego'].replace(renomear_tempo)

df = df.dropna()
df.isnull().sum()
df_limpo = df.assign(Ano = df['Ano'].astype('int64') )
renomear_remoto = {100 : 'remoto', 50 : 'hibrido', 0 : 'presencial'}
df_limpo['remoto'] = df_limpo['remoto'].replace(renomear_remoto)



df.head()